name: Publish to Artifactory
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-publish:
    name: Docker push to Google Artifact Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-build-and-push
        name: Docker build and push to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.ARTIFACT_REGISTRY_URL }}/rclone-tinyproxy:latest
